safe:             false
port:             7999
baseurl:          /Kyruus-Bootstrap/  # Where GitHub serves the project up from
url:              http://localhost:7999

source:           src
destination:      _gh_pages
plugins:          src/_plugins

pygments:         true
permalink:        pretty

# ensures SCSS files are compiled
include:          [_*.scss]

kyruus-bootstrap:
  version:            1.0.0


# external libraries
jquery:
  version:        1.9.1
  url:            http://jquery.com
bootstrap:
  version:        2.3.2
  url:            http://getbootstrap.com
fontawesome:
  version:        3.2.1
  url:            http://fontawesome.io
